[ReactJs][exercise][UI]create UI
st-suho/FE-Internship-2021_Trong-Su_FE-Exercise pull request #29
Opened 2021-05-26 15:36 UTC by st-suho

**Description** 
*create UI
depend on previous PR https://github.com/st-suho/FE-Internship-2021_Trong-Su_FE-Exercise/pull/28

2021-05-27 08:38 UTC, st-manhle requested changes
@st-suho check cmts

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/App.tsx
> +import "../src/stylesheet/style.css";
style.css bỏ vào đây làm gì e?

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/apis/mockData.jsx
> +export const mockData = [
mockData này để làm gì?

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +interface IArticleItem {
No, đặt là `PropsInterface`

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +export const ArticleItem = ({item} :IArticleItem) => {
export const ArticleItem = (props: PropsInterface) => {

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +export const ArticleItem = ({item} :IArticleItem) => {
const {item} = props;

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +        <div>
div này có tác dụng gì e?

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +          <span>{item.minsRead} MIN READ</span>
tạo file src/app/core/constants/text.ts rồi define những text cứng vào (như `MINS READ`)

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/tsconfig.json
> +}
endline

2021-05-27 08:38 UTC, st-manhle commented on exercise-react/src/stylesheet/style.scss
> +.article-list {
Sao lại viét vào hết file style.scss này????

2021-05-27 08:39 UTC, st-manhle commented on exercise-react/src/stylesheet/style.scss
> +  padding: 0 200px;
Yêu cầu dùng Rem thay cho px nghe e
Bỏ đoạn code này vào mixin

```
// === CONVERT PXREM ===
@function strip-units($number) {
  @return $number / ($number * 0 + 1);
}

@function convertRootPxToEm($value) {
  // check for null:
  @if($value == null) {
    @return $value;
  }
  // assume em:
  @if (unitless($value) or unit($value) == em) {
    @return 0em + $value;
  }
  @else {
    @return 0em + strip-units($value) / 16;
  }
}

@function convertPxToRem($px) {
  @return 0rem + strip-units($px) / 16;
}

@mixin pxRem($property, $values) {
  // Create a couple of empty lists as output buffers:
  $px-values: ();
  $rem-values: ();

  // Ensure $values is a list.
  @if type-of($values) != 'list' {
    $values: join((), $values);
  }

  // Loop through the $values list:
  @each $value in $values {
    @if type-of($value) == number and (unitless($value) or unit($value) == px) {
    $px-values: join($px-values, 0px + ($value));
      $rem-values: join($rem-values, convertPxToRem($value));
    }
    @else {
    // no conversion:
    $px-values: join($px-values, $value);
    $rem-values: join($rem-values, $value);
    }
  }

  #{$property}: $px-values;

  // don't add media query if it's not needed:
  @if $px-values != $rem-values {
    // @media only all {
      #{$property}: $rem-values;
    // }
  }
}
// == End / Convert Px To Rem
```

Cách dùng:
```
@include pxRem(margin, 10 20 30 40);
@include pxRem(margin, 10);
@include pxRem(margin-top, 10);
```

2021-05-27 08:43 UTC, st-manhle commented on exercise-react/src/App.tsx
> +import "../src/stylesheet/style.css";
E import cái này vào làm gì?

2021-05-27 09:18 UTC, st-suho commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +        <div>
à em sửa bên API mà quên sửa này, em đổi div đó thành li á anh

2021-05-27 10:32 UTC, st-manhle requested changes
@st-suho check cmts

2021-05-27 10:32 UTC, st-manhle commented on exercise-react/src/App.tsx
> +import { Article } from "../src/app/pages/article/containers/ArticleList";
ArticleList chứ sao Article ?

2021-05-27 10:32 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +  const {item} =props
sửa convention

2021-05-27 10:32 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +      <li className="article-list">
sao `li` lại có className là `article-list` nhỉ?

2021-05-27 10:32 UTC, st-manhle commented on exercise-react/.github
> +#### References
cái gì đây man???
nội dung này phải ở trong file `pull_request_template.md` chứ

2021-05-27 10:32 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +          return <ArticleItem item={item} />;
ở đây e thiếu `key`, xem console log coi có báo lỗi k?

2021-05-27 10:32 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_home.scss
> +  @include pxRem(padding, 0 200);
bỏ mixin lên trên cùng nghe

2021-05-27 10:32 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_home.scss
> +  @include pxRem(font-size, 12);
font size cần khai báo trong variable, rồi gọi vào đây dùng

```
$font-size: (
  s: 12px,
  m: 14px,
  ...
);
```

2021-05-27 13:28 UTC, st-manhle requested changes
@st-suho Check cmts

2021-05-27 13:28 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +        {mockData.map((item,index) => {
sai convention

2021-05-27 13:28 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +          return <Article key={index} item={item} />;
dùng id làm key ở đây

2021-05-27 13:28 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +          <img src={homeDecor} alt="home decor" className="img-default" />
dùng image của item chứ sao dùng homeDecor gì đây e

2021-05-27 13:28 UTC, st-manhle commented on exercise-react/src/apis/mockData.jsx
> +      "Ettitude — Beautifully Designed Bamboo Sheets & Sleep Wear-Home Décor Holiday Gift Guide",
`mockData.ts` nghe e, k có `jsx`
dùng '',k dùng dấu ""

2021-05-27 13:28 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +          <span>{item.minsRead} {MIN_READ}</span>
- khai báo 
```
MIN_READ = '{value} MIN READ'
```
- chỗ này viết cho a 1 function `replaceText(text: string, value: string)` để replace 1 chuỗi ký tự trong `text` bởi `value`
  - `text` truyền vào MIN_READ
  - `value` truyền vào item.minsRead
  - Repacle `{value}` trong `MIN_READ` bằng `value`

2021-05-28 01:27 UTC, st-manhle requested changes
check cmt

2021-05-28 01:27 UTC, st-manhle commented on exercise-react/src/apis/mockData.tsx
> +export const mockData = [
`ts` thôi, k có `tsx`, e đâu có viết `xml` trong này

2021-05-28 01:27 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_home.scss
> +.title-decor {
`.title-decor` với `.img-default` bỏ vào trong `.article` nghe e, để ngoài như này sẽ nguy hiểm, dính style cho những chỗ ngoài article đó

2021-05-28 01:27 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +  id:number;
sai convention

2021-05-28 01:27 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +          <span>{replaceText("BY",item.author,true)}</span> <span>{item.createdAt}</span>{" "}
chỗ "BY", "MIN READ" a đã kêu e tạo file `src/app/core/constants/text.ts` để khai báo vào rồi mà?

2021-05-28 01:27 UTC, st-manhle commented on exercise-react/src/app/core/constants/text.ts
> +export const replaceText = (
sai rồi, e đọc kỹ lại chỗ này:
https://github.com/st-suho/FE-Internship-2021_Trong-Su_FE-Exercise/pull/29#discussion_r640623260

2021-05-28 06:12 UTC, st-manhle requested changes
check cmts

2021-05-28 06:12 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +    <>
Fragment này có cần thiét k e?

2021-05-28 06:12 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +const replaceText = (
function nãy vẫn chưa đúng
Xem lại yêu cầu 
https://github.com/st-suho/FE-Internship-2021_Trong-Su_FE-Exercise/pull/29#discussion_r640623260

2021-05-28 06:12 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +        <Article key={item.id} item={item} />
e để key ở đây đồng nghĩa với Article có 2 props: key và item
Sửa lại thành như này
```
{mockData.map((item) => (
    <li key={item.id} className="list-item">
        <Article item={item} />
     </li>
 ))} 
```

2021-05-28 06:12 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +      <li className="article">
chỗ này sửa thành <div>

2021-05-28 06:12 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_home.scss
> +.article {
file này k phải là home mà là articleList.scss

2021-05-28 06:54 UTC, st-suho commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +    <>
<> </> dùng để bao Article Component cho nó hiểu mà anh

2021-05-28 07:21 UTC, st-manhle requested changes
check cmts

2021-05-28 07:21 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +  return text.replace("{value}", value);
dùng '', k dùng ""

2021-05-28 07:21 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +const replaceText = (text: string, value: any) => {
any?

2021-05-28 07:21 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +        <span>{replaceText(BY, item.author)}</span>{" "}
e dùng `{" "}` làm cái gì v e

2021-05-28 07:21 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_articleList.scss
> +.list-item {
chỗ này style cho `.article` chứ đúng k ?

2021-05-28 08:04 UTC, st-manhle requested changes
check cmts

2021-05-28 08:04 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_articleList.scss
> +.list-item {
sao ui của list-item lại ở trong articleList e, cái này nó có tính chất dùng chung mà?
`list-style-type: none;` thì e set cho ul trong file reset nhé

2021-05-28 08:04 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_articleList.scss
> +.infor-article {
cái này HTML ở đâu mà e style v?

2021-05-28 08:27 UTC, merged