[ReactJs][exercise][API]fetch API
st-suho/FE-Internship-2021_Trong-Su_FE-Exercise pull request #30
Opened 2021-05-26 16:40 UTC by st-suho

**Description**
* fetch API 
*  depend on previous PR https://github.com/st-suho/FE-Internship-2021_Trong-Su_FE-Exercise/pull/29

2021-05-30 03:56 UTC, st-manhle requested changes
check cmts

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/apis/article.api.tsx
> +const url = "https://6088e20da6f4a300174271e7.mockapi.io/articles";
e lưu `https://6088e20da6f4a300174271e7.mockapi.io` trong file .env đi S

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/apis/article.api.tsx
> +  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmZjNWViNThlZWU2MDc5YmY1YzRhM2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MTE3NTc3NTgsImV4cCI6MTYxMTc2Mjc1OH0.kFV5ahwJDiiQuA-cnYaJ1eG9xKDOk1BcDMDnxfln3h9w";
token này ở đâu ra đây e?
a thấy mấy ban kia đâu có dùng cái nãy vẫn get API đc mà

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +export interface IArticle {
E tạo file theo flow này`src/app/core/interface/ArticleInterface.ts` r bỏ cái IArticle vào trong đó

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +import React, { useEffect, useState } from "react";
sao a vẫn thấy "" trong js nhỉ

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +      .then((res:any) => {
NOT any

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +      .then((res:any) => {
sai convention

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +      .catch((err:Error) => {});
sai convention

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +  const [list, setList] = useState([]);
e cần khai báo interface cho list.

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/ArticleList.tsx
> +      {list.map((item: IArticle) => (
khai báo interface cho list ở trên rồi nên k cần khai báo cho item

2021-05-30 03:56 UTC, st-manhle commented on exercise-react/src/stylesheet/pages/_home.scss
> +.title-decor {
`.title-decor` và `.img-default` nếu là của article thì bỏ vào trong `.article` nghe e

2021-05-30 03:57 UTC, st-manhle commented
Description chưa đúng với template bữa trước a đưa

2021-05-30 12:50 UTC, st-suho commented on exercise-react/src/apis/article.api.tsx
> +  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmZjNWViNThlZWU2MDc5YmY1YzRhM2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MTE3NTc3NTgsImV4cCI6MTYxMTc2Mjc1OH0.kFV5ahwJDiiQuA-cnYaJ1eG9xKDOk1BcDMDnxfln3h9w";
Token đó từ API anh Quân gửi á anh, em để đó dùng nếu có post,put..  rồi dùng á anh, nếu anh muốn thì em xóa thôi anh :D

2021-05-31 01:34 UTC, st-manhle commented on exercise-react/src/apis/article.api.tsx
> +  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmZjNWViNThlZWU2MDc5YmY1YzRhM2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MTE3NTc3NTgsImV4cCI6MTYxMTc2Mjc1OH0.kFV5ahwJDiiQuA-cnYaJ1eG9xKDOk1BcDMDnxfln3h9w";
để vậy đi e

2021-05-31 01:37 UTC, st-manhle requested changes
check cmts

2021-05-31 01:37 UTC, st-manhle commented on exercise-react/.env
> +REACT_APP_BASE_URL = https://6088e20da6f4a300174271e7.mockapi.io/articles
endline

2021-05-31 01:37 UTC, st-manhle commented on exercise-react/src/app/core/interface/ArticleInterface.ts
> +export interface PropsInterface {
k e, cái này e phải để bên component á. chứ để vậy biết props nào

2021-05-31 01:37 UTC, st-manhle commented on exercise-react/src/app/core/interface/ArticleInterface.ts
> +export interface ResInterface {
như trên, để trong component

2021-05-31 01:37 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
>  import React from "react";
còn "" nè e

2021-05-31 01:47 UTC, st-manhle commented on exercise-react/src/app/core/interface/ArticleInterface.ts
> +export interface ResInterface {
sao e chưa xoá cái này luôn

2021-05-31 08:21 UTC, st-manhle requested changes
check cmts

2021-05-31 08:21 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +          <span>{replaceText.replaceTextConst(EST, `${dayTime.showFullDayMonthYear(item.createdAt)} ${dayTime.showFullHourMinuteSecond(item.createdAt)}`)}</span>
sao e k viết function giải quyết cho date vs time luôn, tách ra làm gì e

2021-05-31 08:21 UTC, st-manhle commented on exercise-react/src/App.tsx
> +import { ArticleList } from "./app/pages/article/containers/ArticleList";
sao vẫn còn `"` đây e, refactor lại hết cho a nghe

2021-05-31 08:21 UTC, st-manhle commented on exercise-react/src/app/core/functions/dayTime.ts
> +  return `0${day}`.slice(-2) + '/' + `0${month}`.slice(-2) + '/' + `0${year}`.slice(-2)
sao e k slice trên chỗ e tạo biến luôn

2021-05-31 08:21 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +import { replaceText, dayTime } from '../../../core/functions/index';
chỗ này k cần `/index` đâu e

2021-05-31 08:21 UTC, st-manhle commented on exercise-react/src/app/pages/article/containers/Article.tsx
> +import '../../../../stylesheet/style.css';
cái css này import bên App e nghe

2021-05-31 10:51 UTC, st-manhle requested changes
check cmts

2021-05-31 10:51 UTC, st-manhle commented on exercise-react/src/apis/article.api.tsx
> +const axios = require("axios");
es5?

2021-05-31 10:51 UTC, st-manhle commented on exercise-react/src/apis/article.api.tsx
> +const baseUrl = process.env.REACT_APP_BASE_URL
tên env k đúng, tham khảo: API_ENDPOINT_URL hoặc API_BASE_URL

2021-05-31 10:51 UTC, st-manhle commented on exercise-react/.env
> +REACT_APP_BASE_URL = https://6088e20da6f4a300174271e7.mockapi.io/articles
Link này dùng chung ở những chỗ khác mà e /articles là sai
Nếu a muốn get api `https://6088e20da6f4a300174271e7.mockapi.io/users`  thì sao?

2021-05-31 10:51 UTC, st-manhle commented on exercise-react/src/apis/article.api.tsx
> +const axios = require("axios");
đổi tên file thành flow như sau
`app/core/services/api.service.ts`
Update để file này thành 1 service dùng chung cho tất cả các api, k riêng chi article

2021-05-31 10:51 UTC, st-manhle commented on exercise-react/src/apis/article.api.tsx
> +export const getArticle = () => {
đổi thành `getApi(uri: string)`
```
return axios.get(`${baseUrl}${uri}`, {headers: ....}});
```

2021-05-31 14:26 UTC, merged